obj-m := duet_p1_video_raw.o
duet_p1_video_raw-y := duet_p1_continuous.o duet_p1_abi.o duet_p1_stop.o duet_p1_stream_codec.o duet_p1_stream.o duet_p1_bqueue.o duet_p1_adapter.o duet_p1_hw.o duet_p1_workers.o duet_p1_handoff.o camera_video.o camera_raw.o
