obj-m := mt8183_p1.o
mt8183_p1-y := mt8183_p1_continuous.o mt8183_p1_abi.o mt8183_p1_stop.o mt8183_p1_stream_codec.o mt8183_p1_stream.o mt8183_p1_bqueue.o mt8183_p1_adapter.o mt8183_p1_hw.o mt8183_p1_workers.o mt8183_p1_handoff.o camera_video.o camera_raw.o
